# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# INFO: https://github.com/googleapis/release-please-action
name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: simple
